spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: junelienonsalamanca08@gmail.com     # <-- replace with your actual email
    password: faou ozna lvts dzpg       # <-- replace with your generated app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true                    # debug is at the same level as smtp (not nested under starttls)
server:
  port: 8080


